# Generated by Django 4.0.5 on 2022-06-10 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Sku')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('precio', models.CharField(blank=True, max_length=20, null=True, verbose_name='precio')),
                ('stock', models.CharField(blank=True, max_length=20, null=True, verbose_name='stock')),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True, verbose_name='descripcion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
